matrix:
  - name: Spell Checking
    aspell:
      lang: en
      d: en_US
      camel-case: true
    dictionary:
      output: /tmp/dinao-pyspelling.dic
      wordlists:
        - .pyspelling.xdic
    sources:
      - ./dinao/**/*.py
      - ./*.md
      - ./dinao/LICENSE
      - ./examples/**/*.md
      - ./examples/**/*.py
    pipeline:
      - pyspelling.filters.url:
