version: "3.7"

services:

  postgres:
    image: postgres:latest
    command: >
      -c ssl=on
      -c ssl_cert_file=/var/lib/postgresql/server.crt
      -c ssl_key_file=/var/lib/postgresql/server.key
    environment:
      POSTGRES_USER: psql_test_user
      POSTGRES_PASSWORD: psql_test_pass
    volumes:
      - ./vols/tls/server.crt:/var/lib/postgresql/server.crt
      - ./vols/tls/server.key:/var/lib/postgresql/server.key
    ports:
      - "15432:5432"

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: mysql_test_root_pass
      MYSQL_USER: mysql_test_user
      MYSQL_PASSWORD: mysql_test_pass
    volumes:
      - ./vols/mariadb/99-ssl.cnf:/etc/mysql/mariadb.conf.d/99-ssl.cnf
      - ./vols/tls/server.crt:/certs/server.crt
      - ./vols/tls/server.key:/certs/server.key
    ports:
      - "23306:3306"

  mariadb:
    image: mariadb:latest
    environment:
      MARIADB_ROOT_PASSWORD: maria_test_root_pass
      MARIADB_USER: maria_test_user
      MARIADB_PASSWORD: maria_test_pass
    volumes:
      - ./vols/mariadb/99-ssl.cnf:/etc/mysql/mariadb.conf.d/99-ssl.cnf
      - ./vols/tls/server.crt:/certs/server.crt
      - ./vols/tls/server.key:/certs/server.key
    ports:
      - "13306:3306"
